name: car_play
description: Flutter Apps are now on Apple CarPlay. This package aims to make it safe to use iPhone apps made with Flutter in the car by integrating with CarPlay.
version: 1.0.5
homepage: https://github.com/jorditoda/flutter_carplay#readme
repository: https://github.com/jorditoda/flutter_carplay
issue_tracker: https://github.com/jorditoda/flutter_carplay/issues

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterCarplayPlugin
